// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CreateInterfaceVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "CreateInterfaceVSIX.2292ba77-2fda-4982-8108-0e032451e914";
        public const string Name = "CreateInterfaceVSIX";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Taner Saydam";
        public const string Tags = "";
    }
}
